# Generated by Django 4.1.1 on 2022-09-28 12:21

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[students.validators.validate_unique_phone]),
        ),
    ]
