# Generated by Django 4.1.1 on 2022-09-26 09:15

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidEmailDomain('@mail.com', '@gmail.com', '@yahoo.com')]),
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
