# Generated by Django 4.1.1 on 2022-09-28 12:22

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0003_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True,
                                   validators=[core.validators.validate_unique_phone]),
        ),
    ]
