# Generated by Django 4.1.1 on 2022-09-26 12:38

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_email_alter_student_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidEmailDomain('@mail.com', '@gmail.com', '@yahoo.com'), students.validators.validate_unique_email]),
        ),
    ]
