# Generated by Django 4.1.2 on 2022-10-10 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_group_description'),
        ('students', '0004_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2022-10-07 21:28:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
