# Generated by Django 4.1.2 on 2022-10-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0009_group_headman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_column='course name', max_length=40)),
                ('duration', models.CharField(max_length=10)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('course_description', models.CharField(blank=True, db_column='description', max_length=200, null=True)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='groups.group')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
