# Generated by Django 4.1.2 on 2022-10-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('python', 'Python Basics'), ('pythonA', 'Python Advanced')], db_column='course name', max_length=40, verbose_name='course name'),
        ),
    ]
