# Generated by Django 4.1.2 on 2022-10-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('fe', 'Front-End basics'), ('feA', 'Front-End Advanced'), ('hr', 'HR Generalist in IT'), ('Java', 'Java Basic'), ('JavaA', 'Java Advanced'), ('qa', 'QA Manual'), ('qaa', 'QA Automation'), ('python', 'Python Basics'), ('pythonA', 'Python Advanced'), ('ux', 'UI/UX Design'), ('uxP', 'UI/UX Design')], db_column='course name', max_length=40, verbose_name='course name'),
        ),
    ]
