# Generated by Django 4.1.1 on 2022-09-26 12:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='group_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"group_name" field value less than two symbols')], verbose_name='group name')),
                ('group_start_date', models.DateField(blank=True, db_column='group_start_date', default=datetime.date.today, null=True, verbose_name='group start date')),
                ('group_description', models.CharField(blank=True, db_column='group_description', max_length=600, null=True, verbose_name='group description')),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
