# Generated by Django 4.1.2 on 2022-10-18 09:51

import datetime
import django.core.validators
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(db_column='group_name', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '"group_name" field value less than two symbols')], verbose_name='group name')),
                ('group_start_date', models.DateField(db_column='group_start_date', default=datetime.date.today, validators=[groups.validators.validate_start_date], verbose_name='group start date')),
                ('group_description', models.CharField(choices=[('fe', 'Front-End'), ('hr', 'HR'), ('j', 'Java'), ('qa', 'QA Manual'), ('qaA', 'QA Automation'), ('pt', 'Python'), ('ux', 'UI/UX Design')], db_column='group_description', max_length=600, verbose_name='group description')),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
