# Generated by Django 4.1.2 on 2022-10-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(blank=True, choices=[('fe', 'Front-End'), ('hr', 'HR'), ('j', 'Java'), ('qa', 'QA Manual'), ('qaA', 'QA Automation'), ('pt', 'Python'), ('ux', 'UI/UX Design')], db_column='group_description', max_length=600, null=True, verbose_name='group description'),
        ),
    ]
