# Generated by Django 4.1.1 on 2022-09-30 10:13

import datetime
from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_group_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(db_column='group_description', default='test', max_length=600, verbose_name='group description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_start_date',
            field=models.DateField(db_column='group_start_date', default=datetime.date.today, validators=[groups.validators.validate_start_date], verbose_name='group start date'),
        ),
    ]
