# Generated by Django 4.1.1 on 2022-09-30 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_group_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_start_date',
            field=models.DateField(db_column='group_start_date', default=datetime.date.today, verbose_name='group start date'),
        ),
    ]
