# Generated by Django 4.1.1 on 2022-09-30 13:15

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0007_alter_group_group_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(db_column='group_description', default='test', max_length=600,
                                   validators=[core.validators.validate_group_description],
                                   verbose_name='group description'),
        ),
    ]
