# Generated by Django 4.1.2 on 2022-10-14 11:27

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_group_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(db_column='group_description', max_length=600, validators=[core.validators.validate_group_description], verbose_name='group description'),
        ),
    ]
