# Generated by Django 4.1.2 on 2022-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_alter_group_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.CharField(choices=[('fe', 'Front-End'), ('hr', 'HR'), ('j', 'Java'), ('qa', 'QA Manual'), ('qaA', 'QA Automation'), ('pt', 'Python'), ('ux', 'UI/UX Design')], db_column='group_description', max_length=600, verbose_name='group description'),
        ),
    ]
