# Generated by Django 4.1.2 on 2022-10-24 10:36

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_name',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[core.validators.validate_group_description]),
        ),
    ]
