# Generated by Django 4.1.1 on 2022-10-03 09:32

from django.db import migrations, models

import core.validators
import teachers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_email_alter_teacher_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, validators=[core.validators.valid_email_domains, core.validators.validate_unique_email]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[core.validators.validate_unique_phone]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject_name',
            field=models.CharField(max_length=13, validators=[core.validators.validate_group_description]),
        ),
    ]
